language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev qt5-default
  - sudo apt-get install cmake
script:
  - git submodule update --init --recursive
  - cd mupdf && make && cd ..
  - mkdir build && cd build && cmake .. && make
  - wget http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf
  - ./bin/countpages pdf_reference_1-7.pdf
  - ./bin/exportpage pdf_reference_1-7.pdf 1
  - ./bin/qimage pdf_reference_1-7.pdf
  - ./bin/showinfo pdf_reference_1-7.pdf
  - ./bin/showtext pdf_reference_1-7.pdf 1
  - ./bin/outline pdf_reference_1-7.pdf
  - ./bin/test_document pdf_reference_1-7.pdf
  - ./bin/test_page pdf_reference_1-7.pdf
branches:
  only:
    - master
    - dev
notifications:
  recipients:
    - xiangxw5689@126.com
  email:
    on_success: change
    on_failure: always
